### ISSUE TITLE
fail: Microsoft.AspNetCore.Session.SessionMiddleware[1]

### ISSUE THREAD

**Issue by dataangel** [AppSpaceIT/MongoDbCache#1]
Shielding "_mongoContext.GetCacheItemAsync(key, withoutValue: true)“ is good  
_mongoContext.GetCacheItemAsync > GetItemQuery > query.Project<CacheItem>(Builders<CacheItem>.Projection.Exclude(x => x.Value))
fail: Microsoft.AspNetCore.Session.SessionMiddleware[1]
      Error closing the session.
MongoDB.Bson.BsonSerializationException: No matching creator found.
   在 MongoDB.Bson.Serialization.BsonClassMapSerializer`1.ChooseBestCreator(Dictionary`2 values)
   在 MongoDB.Bson.Serialization.BsonClassMapSerializer`1.CreateInstanceUsingCreator(Dictionary`2 values)
   在 MongoDB.Bson.Serialization.BsonClassMapSerializer`1.DeserializeClass(BsonDeserializationContext context)
   在 MongoDB.Bson.Serialization.BsonClassMapSerializer`1.Deserialize(BsonDeserializationContext context, BsonDeserializationArgs args)

^o^

**Comment by petrhaus** [comment]
Thanks for reporting this, it should be fixed now.
Nuget package updated to version 0.3.4-rc2.
