### ISSUE TITLE
Only .Net Core 2.2 is used as target which is not supported anymore by Microsoft.

### ISSUE THREAD

**Issue by iBrotNano** [AppSpaceIT/MongoDbCache#12]
Only .NET Core 2.2 is supported as a build target. It is outdated and does not get any security updated by Microsoft anymore. Is there any readon why 2.2 is used explicitly? I made a fork and it seems that i could set netstandard2.0 as the build target which would target .NET Framework and .NET both.

All tests are running green.

**Comment by petrhaus** [comment]
Thanks, published on nuget as version 2.5.0
