### ISSUE TITLE
Expire Data from Collections Using TTL and Capped Collections

### ISSUE THREAD

**Issue by adamfisher** [AppSpaceIT/MongoDbCache#6]
MongoDB exposes a built-in "time to live" or [TTL collection feature](https://docs.mongodb.com/manual/tutorial/expire-data/). Why not use this to expire items instead of making the application server handle the expirations?

Also the notion of [capped collections](https://docs.mongodb.com/manual/core/capped-collections) may prove interesting for cache storage as well so users can control the size of the cache and behind the scenes, MongoDB takes care of treating the cache like a circular buffer.

**Comment by petrhaus** [comment]
TTL relies on indexes, and a different expiration implies creating a new index.

Capped collections cannot be used for (at least) two reasons:
- they do not allow deletes (nor modifications, given that you cannot alter the size of the doc)
- they may remove cached items in an unpredicable way

:-)

**Comment by ghost** [comment]
You can specify a TTL index with an expireAfterSeconds set to 0 which would allow you to specify the expire time in the document using a date field. https://www.mongodb.com/docs/manual/tutorial/expire-data/#expire-documents-at-a-specific-clock-time

**Comment by petrhaus** [comment]
Thanks @a146518, I didn't notice it.
I think that this could be easily implemented, but right now I have limited time. What about opening a pull request?
