### ISSUE TITLE
NET Core 3.x support

### ISSUE THREAD

**Issue by vd3d** [AppSpaceIT/MongoDbCache#8]
There are issues in the MongoDB.Driver 2.8, see:
https://jira.mongodb.org/browse/CSHARP-2595

It is related to NET Core 3.x

So, in order to be compatible, we need an update to the last driver, right ?

**Comment by petrhaus** [comment]
Thanks for reporting this!
If you update the driver you will be ok.
In the next few days I will update the project and the nuget package to target 2.8.1, which seems to have the bug solved.
