### ISSUE TITLE
AddDataProtection().PersisKey

### ISSUE THREAD

**Issue by vd3d** [AppSpaceIT/MongoDbCache#9]
Hi,

I use MongoDbCache, it replace the StackExchange.Redis library.

The problem is that we have a "Services.AddDataProtection().PersistKeysToStackExchangeRedis" but there is no equivalent for MongoDB.

Can you provides it ?

PS: here is the source code https://github.com/aspnet/DataProtection/blob/master/src/Microsoft.AspNetCore.DataProtection.StackExchangeRedis/RedisDataProtectionBuilderExtensions.cs

**Comment by petrhaus** [comment]
Hi,
support for persisting security keys is implemented in a different package and has nothing to do with caching. I'm not going to mix up things, so I won't add it to this project.
After looking at the source code I'll check if I have time to make it available in a separate project/package or not.

**Comment by petrhaus** [comment]
I'm closing this issue as it is not related to this project
